import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(max_length=20, choices=[
                    ('email', 'Email'),
                    ('sms', 'SMS'),
                    ('social', 'Social Media'),
                    ('content', 'Content'),
                    ('ppc', 'PPC'),
                    ('event', 'Event'),
                ])),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=20, choices=[
                    ('draft', 'Draft'),
                    ('active', 'Active'),
                    ('paused', 'Paused'),
                    ('completed', 'Completed'),
                ])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('target_audience', models.JSONField(default=dict)),
                ('goals', models.JSONField(default=dict)),
                ('tags', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_created', to='core.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_updated', to='core.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('variables', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailtemplate_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailtemplate_created', to='core.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emailtemplate_updated', to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('subject', models.CharField(max_length=255)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('bounce_count', models.IntegerField(default=0)),
                ('unsubscribe_count', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20, choices=[
                    ('draft', 'Draft'),
                    ('scheduled', 'Scheduled'),
                    ('sending', 'Sending'),
                    ('sent', 'Sent'),
                ])),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='marketing.campaign')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.emailtemplate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaignemail_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaignemail_created', to='core.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaignemail_updated', to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaignemail',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='crm.contact'),
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('variant_a', models.JSONField(default=dict)),
                ('variant_b', models.JSONField(default=dict)),
                ('variant_a_results', models.JSONField(default=dict)),
                ('variant_b_results', models.JSONField(default=dict)),
                ('winner', models.CharField(blank=True, max_length=1, choices=[('a', 'A'), ('b', 'B')])),
                ('sample_size', models.IntegerField(default=100)),
                ('confidence_level', models.FloatField(default=0.95)),
                ('status', models.CharField(default='draft', max_length=20, choices=[
                    ('draft', 'Draft'),
                    ('running', 'Running'),
                    ('completed', 'Completed'),
                ])),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='marketing.campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abtest_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abtest_created', to='core.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abtest_updated', to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadNurture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_criteria', models.JSONField(default=dict)),
                ('steps', models.JSONField(default=list)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadnurture_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadnurture_created', to='core.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadnurture_updated', to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('platform', models.CharField(max_length=20, choices=[
                    ('facebook', 'Facebook'),
                    ('twitter', 'Twitter/X'),
                    ('linkedin', 'LinkedIn'),
                    ('instagram', 'Instagram'),
                ])),
                ('content', models.TextField()),
                ('media_urls', models.JSONField(default=list)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20, choices=[
                    ('draft', 'Draft'),
                    ('scheduled', 'Scheduled'),
                    ('published', 'Published'),
                ])),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('ai_sentiment_score', models.FloatField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='marketing.campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialpost_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socialpost_created', to='core.user')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socialpost_updated', to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
