import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('capacity', models.IntegerField(default=0, help_text='Total capacity in units')),
                ('is_primary', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_updated', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcategory_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productcategory_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productcategory_updated', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.productcategory')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('product_type', models.CharField(
                    choices=[('physical', 'Physical'), ('digital', 'Digital'), ('service', 'Service')],
                    default='physical',
                    max_length=20,
                )),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(default='unit', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('min_stock_level', models.IntegerField(default=0)),
                ('max_stock_level', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('reorder_quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('tags', models.JSONField(default=list)),
                ('is_sellable', models.BooleanField(default=True)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('product_role', models.CharField(
                    choices=[('raw_material', 'Raw Material'), ('semi_finished', 'Semi-Finished'), ('finished_good', 'Finished Good')],
                    default='finished_good',
                    max_length=20,
                )),
                ('business_field', models.CharField(
                    blank=True,
                    choices=[('led_lights', 'LED Lights'), ('heater_thermocouple', 'Heater & Thermocouple'), ('solar_ac', 'Solar AC'), ('trade', 'Trade')],
                    max_length=30,
                )),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('company', 'sku')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'sku'], name='inv_product_co_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='inv_product_barcode_idx'),
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('incoming_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('available_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('last_counted', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('product', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('movement_type', models.CharField(
                    choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('return', 'Return')],
                    max_length=20,
                )),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockmovement_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockmovement_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockmovement_updated', to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='inventory.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_movements', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-date'], name='inv_stockmov_prod_date_idx'),
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(
                    choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved')],
                    default='draft',
                    max_length=20,
                )),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventorycount_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventorycount_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventorycount_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('variance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorycount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('forecasted_demand', models.DecimalField(decimal_places=3, max_digits=12)),
                ('actual_demand', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('confidence', models.FloatField(default=0.8)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('factors', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandforecast_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandforecast_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandforecast_updated', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.product')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ProductBOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productbom_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productbom_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productbom_updated', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(
                    limit_choices_to={'product_role__in': ['semi_finished', 'finished_good']},
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='bom',
                    to='inventory.product',
                )),
            ],
            options={
                'verbose_name': 'product BOM',
                'verbose_name_plural': 'product BOMs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_of_measure', models.CharField(default='unit', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.productbom')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='inventory.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCostSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labour_percentage', models.DecimalField(
                    decimal_places=2,
                    default=0,
                    help_text='% of selling price allocated to labour',
                    max_digits=5,
                )),
                ('overhead_percentage', models.DecimalField(
                    decimal_places=2,
                    default=0,
                    help_text='% of selling price allocated to overhead',
                    max_digits=5,
                )),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_setting', to='core.company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_cost', models.DecimalField(
                    decimal_places=4,
                    default=0,
                    help_text='Auto-calculated from BOM lines x unit costs',
                    max_digits=18,
                )),
                ('labour_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('labour_cost', models.DecimalField(
                    decimal_places=4,
                    default=0,
                    help_text='selling_price x labour_percentage / 100',
                    max_digits=18,
                )),
                ('overhead_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overhead_cost', models.DecimalField(
                    decimal_places=4,
                    default=0,
                    help_text='selling_price x overhead_percentage / 100',
                    max_digits=18,
                )),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('gross_profit', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('profit_margin', models.DecimalField(
                    decimal_places=2,
                    default=0,
                    help_text='(gross_profit / selling_price) x 100',
                    max_digits=6,
                )),
                ('currency', models.CharField(default='EGP', max_length=3)),
                ('last_calculated', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdown', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('alert_type', models.CharField(
                    choices=[
                        ('low_stock', 'Low Stock'),
                        ('out_of_stock', 'Out of Stock'),
                        ('low_raw_material', 'Low Raw Material'),
                        ('incoming_delayed', 'Incoming Delayed'),
                    ],
                    max_length=30,
                )),
                ('threshold_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('current_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='acknowledged_alerts',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockalert_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockalert_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockalert_updated', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.product')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['company', 'is_acknowledged'], name='inv_alert_co_ack_idx'),
        ),
        migrations.CreateModel(
            name='InterCompanyTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('transfer_number', models.CharField(max_length=50)),
                ('status', models.CharField(
                    choices=[
                        ('draft', 'Draft'),
                        ('dispatched', 'Dispatched'),
                        ('in_transit', 'In Transit'),
                        ('received', 'Received'),
                        ('cancelled', 'Cancelled'),
                    ],
                    default='draft',
                    max_length=20,
                )),
                ('transfer_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercompanytransfer_set', to='core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercompanytransfer_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercompanytransfer_updated', to=settings.AUTH_USER_MODEL)),
                ('from_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='core.company')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='inventory.warehouse')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='core.company')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='InterCompanyTransferLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.intercompanytransfer')),
            ],
        ),
    ]
